# --- Project Info ---
sonar.projectKey=mentalhealth_project
sonar.projectName=Mental Health Assistant
sonar.projectVersion=1.0

# --- Source Code ---
sonar.sources=client,server,api

# --- Exclusions (important) ---
sonar.exclusions=**/node_modules/**,**/*.log,**/dist/**,**/coverage/**,**/build/**

# --- SonarQube Server (LOCAL) ---
sonar.host.url=http://localhost:9000

# --- Authentication ---
sonar.token=squ_f824d88b7275c9f5c8e4046734ab08ae369d0a19

sonar.javascript.lcov.reportPaths=server/coverage/lcov.info